/**
 * 
 */
package com.fynger.generic.exception.base;


/**
 * @author Rishi
 *
 */
public enum EExceptionTypes {
	
	APPLICATION_EXCEPTION,
	DATABASE_CONNECTION_MANAGER_EXCEPTION,
	PROPERTY_MANAGER_EXCEPTION,
	ACTION_EXCEPTION,
	BUSINESS_EXCEPTION,
	BUSINESS_VALIDATION_EXCEPTION,
	DATA_ACCESS_EXCEPTION,
	INCORRECT_PASSWORD_EXCEPTION,
	USER_NAME_NOT_FOUND_EXCEPTION,
	BAD_REQUEST_EXCEPTION,
	INIT_EXCEPTION,
	SERVICES_EXCEPTION,
	FORGOT_PASSWORD_VERIFICATION_FAILED_EXCEPTION,
	SEARCH_ENGINE_EXCEPTION,
	NO_SEARCH_RESULTS_FOUND_EXCEPTION,
	NO_REVIEWS_FOUND_EXCEPTION,
	LISTING_ID_NOT_FOUND_EXCEPTION,
	PROMOTION_ID_NOT_FOUND_EXCEPTION,
	PROMOTION_EXCEPTION,
	GEO_COORDINATES_NOT_FOUND_EXCEPTION,
	LOCATION_NOT_FOUND_EXCEPTION,
	FLASHDEAL_EXCEPTION,
	NO_FLASHDEAL_RESPONDED_RESULTS_FOUND_EXCEPTION,
	FILE_UPLOAD_FAILED_EXCEPTION,
	FAVOURITES_EXCEPTION,
	ADD_FAVOURITES_EXCEPTION,
	DELETE_FAVOURITES_EXCEPTION,
	NO_FAVOURITES_FOUND_EXCEPTION,
	NO_FAVOURITES_RESULTS_FOUND_EXCEPTION,
	PAGE_COUNT_EXCEEDED_EXCEPTION,
	FB_LOGIN_EXCEPTION,
	THREAD_MANAGER_EXCEPTION,
	MONITOR_FLASH_DEAL_VALIDITY_THREAD_EXCEPTION,
	MONITOR_PROMOTION_VALIDITY_THREAD_EXCEPTION,
	REFRESH_USER_FAVOURITES_SEARCH_RESULTS_THREAD_EXCEPTION,
	SHOUT_GROUP_EXCEPTION

}
