/**
 * 
 */
package com.fynger.servicesBusiness.business.base;

/**
 * @author Rishi
 *
 */
public enum ERequestType {
	
	USER_LOGIN,
	USER_LOGIN_FACEBOOK,
	USER_LOGIN_FACEBOOK_CREATE,
	USER_PROFILE_REGISTRATION,
	USER_PROFILE_LOAD,
	USER_PROFILE_UPDATE,
	USER_PROFILE_FORGOT_PASSWORD_VERIFICATION,
	USER_PROFILE_FORGOT_PASSWORD_UPDATE,
	USER_PROFILE_USERNAME_AVAILABILITY,
	USER_PROFILE_FILE_UPLOAD,
	SEARCH_LISTING_RESULTS_LIST,
	SEARCH_LISTING_RATING,
	SEARCH_LISTING_REVIEW,
	SEARCH_LISTING_LOAD_REVIEWS,
	SEARCH_LISTING_ADD_TO_FAVOURITE,
	SEARCH_PROMOTION_RESULTS_LIST,
	SEARCH_PROMOTION_DETAIL,
	SEARCH_PROMOTION_RATING,
	SEARCH_PROMOTION_REVIEW,
	SEARCH_PROMOTION_LOAD_REVIEWS,
	SEARCH_PROMOTION_ADD_TO_FAVOURITE,
	SEARCH_FLASHDEAL_REQUEST,
	SEARCH_FLASHDEAL_RESULTS_LIST,
	SEARCH_FLASHDEAL_DETAIL,
	SEARCH_FAVOURITES_ADD,
	SEARCH_FAVOURITES_LIST,
	SEARCH_FAVOURITES_DELETE,
	SEARCH_FAVOURITES_RESULTS_LIST,
	SEARCH_FAVOURITES_DETAIL,
	USER_LOGOUT,
	SHOUT_LOAD_DETAILS,
	SHOUT_VIEW_POST_RESPONSES,
	SHOUT_CREATE_POST,
	SHOUT_CREATE_POST_UPLOAD,
	SHOUT_CREATE_POLL,
	SHOUT_REPLY_POST,
	SHOUT_REPLY_POLL,
	PLACE_LOAD_DETAILS,
	PLACE_VIEW_POST_RESPONSES,
	PLACE_CREATE_POST,
	PLACE_CREATE_POST_UPLOAD,
	PLACE_CREATE_POLL,
	PLACE_REPLY_POST,
	PLACE_REPLY_POLL,
	USER_REFRESH_LOCATION

}

